;;; nord-theme.el --- my nord theme -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(deftheme nord)

(let ((class '((class color) (min-colors 89)))
      (nord00 "#2E3440")
      (nord01 "#3B4252")
      (nord02 "#434C5E")
      (nord03 "#4C566A")
      (nord04 "#D8DEE9")
      (nord05 "#E5E9F0")
      (nord06 "#ECEFF4")
      (nord07 "#8FBCBB")
      (nord08 "#88C0D0")
      (nord09 "#81A1C1")
      (nord10 "#5E81AC")
      (nord11 "#BF616A")
      (nord12 "#D08770")
      (nord13 "#EBCB8B")
      (nord14 "#A3BE8C")
      (nord15 "#B48EAD"))
  (custom-theme-set-faces
   'nord
   `(normal ((,class (:weight normal))))
   `(normal-italic ((,class (:weight normal :slant italic))))
   `(default ((,class (:foreground ,nord04 :background ,nord00))))
   `(error ((,class (:foreground ,nord11 :weight normal))))
   `(escape-glyph ((,class (:foreground ,nord12))))
   `(font-lock-builtin-face ((,class (:foreground ,nord09))))
   `(font-lock-comment-face ((,class (:foreground ,nord03 :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:foreground ,nord03))))
   `(font-lock-constant-face ((,class (:foreground ,nord09))))
   `(font-lock-doc-face ((,class (:foreground ,nord03 :slant italic))))
   `(font-lock-function-name-face ((,class (:foreground ,nord08))))
   `(font-lock-keyword-face ((,class (:foreground ,nord09))))
   `(font-lock-negation-char-face ((,class (:foreground ,nord09))))
   `(font-lock-preprocessor-face ((,class (:foreground ,nord10 :weight normal))))
   `(font-lock-reference-face ((,class (:foreground ,nord09))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground ,nord13))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground ,nord13))))
   `(font-lock-string-face ((,class (:foreground ,nord14))))
   `(font-lock-type-face ((,class (:foreground ,nord07))))
   `(font-lock-variable-name-face ((,class (:foreground ,nord04))))
   `(font-lock-warning-face ((,class (:foreground ,nord13))))
   `(italic ((,class (:slant italic))))
   `(shadow ((,class (:foreground ,nord03))))
   `(underline ((,class (:underline t))))
   `(warning ((,class (:foreground ,nord13 :weight normal))))
   `(anzu-mode-line ((,class (:foreground, nord08))))
   `(anzu-mode-line-no-match ((,class (:foreground, nord11))))
   `(avy-lead-face ((,class (:background ,nord11 :foreground ,nord05))))
   `(avy-lead-face-0 ((,class (:background ,nord10 :foreground ,nord05))))
   `(avy-lead-face-1 ((,class (:background ,nord03 :foreground ,nord05))))
   `(avy-lead-face-2 ((,class (:background ,nord15 :foreground ,nord05))))
   `(aw-leading-char-face ((,class (:foreground ,nord11))))
   `(border ((,class (:foreground ,nord04))))
   `(buffer-menu-buffer ((,class (:foreground ,nord04 :weight normal))))
   `(button ((,class (:background ,nord00 :foreground ,nord08 :box (:line-width 2 :color ,nord04 :style sunken-button)))))
   `(c-annotation-face ((,class (:foreground ,nord12))))
   `(company-echo-common ((,class (:foreground ,nord00 :background ,nord04))))
   `(company-preview ((,class (:foreground ,nord04 :background ,nord10))))
   `(company-preview-common ((,class (:foreground ,nord00 :background ,nord08))))
   `(company-preview-search ((,class (:foreground ,nord00 :background ,nord08))))
   `(company-scrollbar-bg ((,class (:foreground ,nord01 :background ,nord01))))
   `(company-scrollbar-fg ((,class (:foreground ,nord02 :background ,nord02))))
   `(company-template-field ((,class (:foreground ,nord00 :background ,nord07))))
   `(company-tooltip ((,class (:foreground ,nord04 :background ,nord02))))
   `(company-tooltip-annotation ((,class (:foreground ,nord12))))
   `(company-tooltip-annotation-selection ((,class (:foreground ,nord12 :weight normal))))
   `(company-tooltip-common ((,class (:foreground ,nord08))))
   `(company-tooltip-common-selection ((,class (:foreground ,nord08 :background ,nord03))))
   `(company-tooltip-mouse ((,class (:inherit highlight))))
   `(company-tooltip-selection ((,class (:background ,nord03 :weight normal))))
   `(completions-annotations ((,class (:foreground ,nord09))))
   `(completions-common-part ((,class (:foreground ,nord08 :weight normal))))
   `(completions-first-difference ((,class (:foreground ,nord11))))
   `(consult-grep-context ((,class (:background ,nord11 :foreground ,nord13))))
   `(consult-highlight-match ((,class (:background ,nord11 :foreground ,nord04))))
   `(consult-line-number ((,class (:foreground ,nord13))))
   `(consult-preview-cursor ((,class (:background ,nord13 :foreground ,nord02))))
   `(consult-preview-insertion ((,class (:background ,nord02))))
   `(consult-preview-match ((,class (:background ,nord11 :foreground ,nord04))))
   `(cursor ((,class (:background ,nord04))))
   `(custom-button ((,class (:background ,nord00 :foreground ,nord08 :box (:line-width 2 :color ,nord04 :style sunken-button)))))
   `(custom-button-mouse ((,class (:background ,nord04 :foreground ,nord00 :box (:line-width 2 :color ,nord04 :style sunken-button)))))
   `(custom-button-pressed ((,class (:background ,nord06 :foreground ,nord00 :box (:line-width 2 :color ,nord04 :style sunken-button)))))
   `(custom-button-pressed-unraised ((,class (:background ,nord04 :foreground ,nord00 :box (:line-width 2 :color ,nord04 :style sunken-button)))))
   `(custom-button-unraised ((,class (:background ,nord00 :foreground ,nord08 :box (:line-width 2 :color ,nord04 :style sunken-button)))))
   `(custom-changed ((,class (:foreground ,nord13))))
   `(custom-comment ((,class (:foreground ,nord03))))
   `(custom-comment-tag ((,class (:foreground ,nord07))))
   `(custom-documentation ((,class (:foreground ,nord04))))
   `(custom-group-tag ((,class (:foreground ,nord08 :weight normal))))
   `(custom-group-tag-1 ((,class (:foreground ,nord08 :weight normal))))
   `(custom-invalid ((,class (:foreground ,nord11))))
   `(custom-modified ((,class (:foreground ,nord13))))
   `(custom-rogue ((,class (:foreground ,nord12 :background ,nord02))))
   `(custom-saved ((,class (:foreground ,nord14))))
   `(custom-set ((,class (:foreground ,nord08))))
   `(custom-state ((,class (:foreground ,nord14))))
   `(custom-themed ((,class (:foreground ,nord08 :background ,nord02))))
   `(diff-added ((,class (:foreground ,nord14))))
   `(diff-changed ((,class (:foreground ,nord13))))
   `(diff-context ((,class (:inherit default))))
   `(diff-file-header ((,class (:foreground ,nord08))))
   `(diff-function ((,class (:foreground ,nord07))))
   `(diff-header ((,class (:foreground ,nord09 :weight normal))))
   `(diff-hl-change ((,class (:background ,nord13))))
   `(diff-hl-delete ((,class (:background ,nord11))))
   `(diff-hl-insert ((,class (:background ,nord14))))
   `(diff-hunk-header ((,class (:foreground ,nord09 :background ,nord00))))
   `(diff-indicator-added ((,class (:foreground ,nord14))))
   `(diff-indicator-changed ((,class (:foreground ,nord13))))
   `(diff-indicator-removed ((,class (:foreground ,nord11))))
   `(diff-nonexistent ((,class (:foreground ,nord11))))
   `(diff-refine-added ((,class (:foreground ,nord14))))
   `(diff-refine-changed ((,class (:foreground ,nord13))))
   `(diff-refine-removed ((,class (:foreground ,nord11))))
   `(diff-removed ((,class (:foreground ,nord11))))
   `(ediff-current-diff-A ((,class (:foreground ,nord06 :background ,nord11))))
   `(ediff-current-diff-Ancestor ((,class (:foreground ,nord06 :background ,nord11))))
   `(ediff-current-diff-B ((,class (:foreground ,nord06 :background ,nord12))))
   `(ediff-current-diff-C ((,class (:foreground ,nord06 :background ,nord10))))
   `(ediff-even-diff-A ((,class (:background ,nord01))))
   `(ediff-even-diff-Ancestor ((,class (:background ,nord01))))
   `(ediff-even-diff-B ((,class (:background ,nord01))))
   `(ediff-even-diff-C ((,class (:background ,nord01))))
   `(ediff-fine-diff-A ((,class (:foreground ,nord06 :background ,nord14 :weight normal))))
   `(ediff-fine-diff-Ancestor ((,class (:foreground ,nord06 :background ,nord14 weight normal))))
   `(ediff-fine-diff-B ((,class (:foreground ,nord06 :background ,nord15 :weight normal))))
   `(ediff-fine-diff-C ((,class (:foreground ,nord06 :background ,nord13 :weight normal))))
   `(ediff-odd-diff-A ((,class (:background ,nord02))))
   `(ediff-odd-diff-Ancestor ((,class (:background ,nord02))))
   `(ediff-odd-diff-B ((,class (:background ,nord02))))
   `(ediff-odd-diff-C ((,class (:background ,nord02))))
   `(elixir-atom-face ((,class (:foreground ,nord04 :weight normal))))
   `(elixir-attribute-face ((,class (:foreground ,nord12))))
   `(enh-ruby-heredoc-delimiter-face ((,class (:foreground ,nord14))))
   `(enh-ruby-op-face ((,class (:foreground ,nord09))))
   `(enh-ruby-regexp-delimiter-face ((,class (:foreground ,nord13))))
   `(enh-ruby-regexp-face ((,class (:foreground ,nord13))))
   `(enh-ruby-string-delimiter-face ((,class (:foreground ,nord14))))
   `(erm-syn-errline ((,class (:foreground ,nord11 :underline t))))
   `(erm-syn-warnline ((,class (:foreground ,nord13 :underline t))))
   `(eshell-ls-archive ((,class (:bold t :foreground ,nord12))))
   `(eshell-ls-backup ((,class (:foreground ,nord03))))
   `(eshell-ls-clutter ((,class (:foreground ,nord04))))
   `(eshell-ls-directory ((,class (:bold t :foreground ,nord11))))
   `(eshell-ls-executable ((,class (:foreground ,nord14))))
   `(eshell-ls-missing ((,class (:foreground ,nord07))))
   `(eshell-ls-product ((,class (:foreground ,nord13))))
   `(eshell-ls-readonly ((,class (:foreground ,nord03))))
   `(eshell-ls-special ((,class (:foreground ,nord13))))
   `(eshell-ls-symlink ((,class (:underline t :foreground ,nord08))))
   `(eshell-ls-unreadable ((,class (:foreground ,nord15))))
   `(evil-ex-info ((,class (:foreground ,nord08))))
   `(evil-ex-substitute-matches ((,class (:inherit isearch))))
   `(evil-ex-substitute-replacement ((,class (:foreground ,nord09))))
   `(file-name-shadow ((,class (:inherit shadow))))
   `(font-latex-italic-face ((,class (:inherit italic))))
   `(font-latex-italic-face ((,class (:slant italic))))
   `(font-latex-match-reference-keywords ((,class (:foreground ,nord09))))
   `(font-latex-match-variable-keywords ((,class (:foreground ,nord04))))
   `(font-latex-math-face ((,class (:foreground ,nord08))))
   `(font-latex-normal-face ((,class (:inherit normal))))
   `(font-latex-normal-face ((,class (:inherit normal))))
   `(font-latex-script-char-face ((,class (:inherit font-lock-warning-face))))
   `(font-latex-sectioning-0-face ((,class (:foreground ,nord08 :weight normal))))
   `(font-latex-sectioning-1-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-2-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-3-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-4-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-5-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-string-face ((,class (:foreground ,nord14))))
   `(font-latex-string-face ((,class (:inherit font-lock-string-face))))
   `(font-latex-warning-face ((,class (:inherit font-lock-warning-face))))
   `(fringe ((,class (:foreground ,nord04 :background ,nord00))))
   `(git-gutter+-added ((,class (:foreground ,nord14))))
   `(git-gutter+-deleted ((,class (:foreground ,nord11))))
   `(git-gutter+-modified ((,class (:foreground ,nord13))))
   `(git-gutter:added ((,class (:foreground ,nord14))))
   `(git-gutter:deleted ((,class (:foreground ,nord11))))
   `(git-gutter:modified ((,class (:foreground ,nord13))))
   `(header-line ((,class (:foreground ,nord04 :background ,nord02))))
   `(helm-bookmark-addressbook ((,class (:foreground ,nord07))))
   `(helm-bookmark-directory ((,class (:foreground ,nord09))))
   `(helm-bookmark-file ((,class (:foreground ,nord08))))
   `(helm-bookmark-gnus ((,class (:foreground ,nord10))))
   `(helm-bookmark-info ((,class (:foreground ,nord14))))
   `(helm-bookmark-man ((,class (:foreground ,nord04))))
   `(helm-bookmark-w3m ((,class (:foreground ,nord09))))
   `(helm-buffer-directory ((,class (:foreground ,nord09))))
   `(helm-buffer-file ((,class (:foreground ,nord08))))
   `(helm-buffer-not-saved ((,class (:foreground ,nord13))))
   `(helm-buffer-process ((,class (:foreground ,nord10))))
   `(helm-candidate-number ((,class (:foreground ,nord13 :weight normal))))
   `(helm-candidate-number-suspended ((,class (:foreground ,nord04))))
   `(helm-codesearch-file-face ((,class (:foreground ,nord14 :slant italic))))
   `(helm-codesearch-lineno-face ((,class (:foreground ,nord13))))
   `(helm-codesearch-source-face ((,class (:foreground ,nord03))))
   `(helm-ff-directory ((,class (:foreground ,nord09 :weight normal))))
   `(helm-ff-dirs ((,class (:foreground ,nord09))))
   `(helm-ff-dotted-directory ((,class (:foreground ,nord09))))
   `(helm-ff-dotted-symlink-directory ((,class (:foreground ,nord07 :weight normal))))
   `(helm-ff-executable ((,class (:foreground ,nord08))))
   `(helm-ff-file ((,class (:foreground ,nord04))))
   `(helm-ff-file-extension ((,class (:foreground ,nord13))))
   `(helm-ff-invalid-symlink ((,class (:foreground ,nord11 :weight normal))))
   `(helm-ff-prefix ((,class (:foreground ,nord00 :background ,nord09))))
   `(helm-ff-symlink ((,class (:foreground ,nord07))))
   `(helm-grep-cmd-line ((,class (:foreground ,nord04 :background ,nord00))))
   `(helm-grep-file ((,class (:foreground ,nord08))))
   `(helm-grep-finish ((,class (:foreground ,nord05))))
   `(helm-grep-lineno ((,class (:foreground ,nord04))))
   `(helm-grep-match ((,class (:inherit isearch))))
   `(helm-grep-running ((,class (:foreground ,nord08))))
   `(helm-header ((,class (:foreground ,nord09 :background ,nord02))))
   `(helm-header-line-left-margin ((,class (:foreground ,nord09 :background ,nord02))))
   `(helm-history-deleted ((,class (:foreground ,nord11))))
   `(helm-history-remote ((,class (:foreground ,nord04))))
   `(helm-lisp-completion-info ((,class (:foreground ,nord04 :weight normal))))
   `(helm-lisp-show-completion ((,class (:inherit isearch))))
   `(helm-locate-finish ((,class (:foreground ,nord14))))
   `(helm-match ((,class (:foreground ,nord08))))
   `(helm-match-item ((,class (:inherit isearch))))
   `(helm-moccur-buffer ((,class (:foreground ,nord08))))
   `(helm-resume-need-update ((,class (:foreground ,nord00 :background ,nord13))))
   `(helm-selection ((,class (:inherit highlight))))
   `(helm-selection-line ((,class (:background ,nord02))))
   `(helm-separator ((,class (:background ,nord02))))
   `(helm-source-header ((,class (:height 1.44 :foreground ,nord08 :background ,nord02))))
   `(helm-visible-mark ((,class (:background ,nord02))))
   `(help-argument-name ((,class (:foreground ,nord08))))
   `(highlight ((,class (:foreground ,nord08 :background ,nord02))))
   `(highlight-symbol-face ((,class (:foreground ,nord13 :background ,nord01))))
   `(hl-line ((,class (:background ,nord01))))
   `(ido-first-match ((,class (:foreground ,nord08 :weight normal))))
   `(ido-only-match ((,class (:foreground ,nord08))))
   `(ido-subdir ((,class (:foreground ,nord09))))
   `(info-menu-star ((,class (:foreground ,nord09))))
   `(isearch ((,class (:foreground ,nord00 :background ,nord08))))
   `(isearch-fail ((,class (:foreground ,nord11))))
   `(ivy-action ((,class (:foreground ,nord10))))
   `(ivy-confirm-face ((,class (:foreground ,nord10))))
   `(ivy-current-match ((,class (:background ,nord10 :foreground ,nord04))))
   `(ivy-match-required-face ((,class (:foreground ,nord10))))
   `(ivy-minibuffer-match-face-1 ((,class (:foreground ,nord10))))
   `(ivy-minibuffer-match-face-2 ((,class (:foreground ,nord10))))
   `(ivy-minibuffer-match-face-3 ((,class (:foreground ,nord10))))
   `(ivy-minibuffer-match-face-4 ((,class (:foreground ,nord10))))
   `(ivy-virtual ((,class (:foreground ,nord10))))
   `(jdee-bug-breakpoint-cursor ((,class (:background ,nord02))))
   `(jdee-db-active-breakpoint-face ((,class (:background ,nord02 :weight normal))))
   `(jdee-db-requested-breakpoint-face ((,class (:foreground ,nord13 :background ,nord02 :weight normal))))
   `(jdee-db-spec-breakpoint-face ((,class (:foreground ,nord14 :background ,nord02 :weight normal))))
   `(jdee-font-lock-api-face ((,class (:foreground ,nord04))))
   `(jdee-font-lock-code-face ((,class (:slant italic))))
   `(jdee-font-lock-constant-face ((,class (:foreground ,nord09))))
   `(jdee-font-lock-constructor-face ((,class (:foreground ,nord08))))
   `(jdee-font-lock-doc-tag-face ((,class (:foreground ,nord07))))
   `(jdee-font-lock-link-face ((,class (:underline t))))
   `(jdee-font-lock-modifier-face ((,class (:foreground ,nord09))))
   `(jdee-font-lock-number-face ((,class (:foreground ,nord15))))
   `(jdee-font-lock-operator-fac ((,class (:foreground ,nord09))))
   `(jdee-font-lock-package-face ((,class (:foreground ,nord07))))
   `(jdee-font-lock-pre-face ((,class (:foreground ,nord03 :slant italic))))
   `(jdee-font-lock-private-face ((,class (:foreground ,nord09))))
   `(jdee-font-lock-public-face ((,class (:foreground ,nord09))))
   `(jdee-font-lock-variable-face ((,class (:foreground ,nord04))))
   `(js2-error ((,class (:foreground ,nord11))))
   `(js2-external-variable ((,class (:foreground ,nord04))))
   `(js2-function-call ((,class (:foreground ,nord08))))
   `(js2-function-param ((,class (:foreground ,nord04))))
   `(js2-instance-member ((,class (:foreground ,nord04))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,nord06))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground ,nord09))))
   `(js2-jsdoc-tag ((,class (:foreground ,nord07))))
   `(js2-jsdoc-type ((,class (:foreground ,nord07))))
   `(js2-jsdoc-value ((,class (:foreground ,nord03))))
   `(js2-object-property ((,class (:foreground ,nord04))))
   `(js2-private-function-call ((,class (:foreground ,nord08))))
   `(js2-private-member ((,class (:foreground ,nord04))))
   `(js2-warning ((,class (:foreground ,nord13))))
   `(js3-error-face ((,class (:foreground ,nord11))))
   `(js3-external-variable-face ((,class (:foreground ,nord04))))
   `(js3-function-param-face ((,class (:foreground ,nord04))))
   `(js3-instance-member-face ((,class (:foreground ,nord04))))
   `(js3-jsdoc-html-tag-delimiter-face ((,class (:foreground ,nord06))))
   `(js3-jsdoc-html-tag-name-face ((,class (:foreground ,nord09))))
   `(js3-jsdoc-tag-face ((,class (:foreground ,nord09))))
   `(js3-jsdoc-type-face ((,class (:foreground ,nord07))))
   `(js3-jsdoc-value-face ((,class (:foreground ,nord04))))
   `(js3-magic-paren-face ((,class (:inherit show-paren-match-face))))
   `(js3-private-function-call-face ((,class (:foreground ,nord08))))
   `(js3-private-member-face ((,class (:foreground ,nord04))))
   `(js3-warning-face ((,class (:foreground ,nord13))))
   `(link ((,class (:underline t))))
   `(link-visited ((,class (:underline t))))
   `(linum ((,class (:foreground ,nord03 :background ,nord00))))
   `(linum-relative-current-face ((,class (:foreground ,nord03 :background ,nord00))))
   `(lsp-ui-sideline-code-action ((,class (:foreground ,nord11))))
   `(magit-branch ((,class (:foreground ,nord07 :weight normal))))
   `(magit-diff-added ((,class (:foreground ,nord14))))
   `(magit-diff-added-highlight ((,class (:foreground ,nord14 :background ,nord02))))
   `(magit-diff-context-highlight ((,class (:background ,nord02))))
   `(magit-diff-file-header ((,class (:foreground ,nord08 :box (:color ,nord08)))))
   `(magit-diff-removed ((,class (:foreground ,nord11))))
   `(magit-diff-removed-highlight ((,class (:foreground ,nord11 :background ,nord02))))
   `(magit-diffstat-added ((,class (:foreground ,nord14))))
   `(magit-diffstat-removed ((,class (:foreground ,nord11))))
   `(magit-hash ((,class (:foreground ,nord08))))
   `(magit-hunk-heading ((,class (:foreground ,nord09))))
   `(magit-hunk-heading-highlight ((,class (:foreground ,nord09 :background ,nord02))))
   `(magit-item-highlight ((,class (:foreground ,nord08 :background ,nord02))))
   `(magit-log-author ((,class (:foreground ,nord07))))
   `(magit-process-ng ((,class (:foreground ,nord13 :weight normal))))
   `(magit-process-ok ((,class (:foreground ,nord14 :weight normal))))
   `(magit-section-heading ((,class (:foreground ,nord07 :weight normal))))
   `(magit-section-highlight ((,class (:background ,nord02))))
   `(markdown-blockquote-face ((,class (:foreground ,nord03))))
   `(markdown-header-face-1 ((,class (:foreground ,nord08))))
   `(markdown-header-face-2 ((,class (:foreground ,nord08))))
   `(markdown-header-face-3 ((,class (:foreground ,nord08))))
   `(markdown-header-face-4 ((,class (:foreground ,nord08))))
   `(markdown-header-face-5 ((,class (:foreground ,nord08))))
   `(markdown-header-face-6 ((,class (:foreground ,nord08))))
   `(markdown-inline-code-face ((,class (:foreground ,nord07))))
   `(markdown-italic-face ((,class (:inherit italic))))
   `(markdown-link-face ((,class (:foreground ,nord08))))
   `(markdown-markup-face ((,class (:foreground ,nord09))))
   `(markdown-normal-face ((,class (:inherit normal))))
   `(markdown-reference-face ((,class (:inherit markdown-link-face))))
   `(markdown-url-face ((,class (:foreground ,nord04 :underline t))))
   `(match ((,class (:inherit isearch))))
   `(message-cited-text ((,class (:foreground ,nord04))))
   `(message-header-cc ((,class (:foreground ,nord09))))
   `(message-header-name ((,class (:foreground ,nord07))))
   `(message-header-newsgroup ((,class (:foreground ,nord14))))
   `(message-header-other ((,class (:foreground ,nord04))))
   `(message-header-subject ((,class (:foreground ,nord08))))
   `(message-header-to ((,class (:foreground ,nord09))))
   `(message-header-xheader ((,class (:foreground ,nord13))))
   `(message-mml ((,class (:foreground ,nord10))))
   `(message-separator ((,class (:inherit shadow))))
   `(minibuffer-prompt ((,class (:foreground ,nord08 :weight normal))))
   `(mm-command-output ((,class (:foreground ,nord08))))
   `(mode-line ((,class (:foreground ,nord08 :background ,nord03))))
   `(mode-line-buffer-id ((,class (:weight normal))))
   `(mode-line-highlight ((,class (:inherit highlight))))
   `(mode-line-inactive ((,class (:foreground ,nord04 :background ,nord03))))
   `(mu4e-flagged-face ((,class (:foreground ,nord13))))
   `(mu4e-header-key-face ((,class (:foreground ,nord08))))
   `(mu4e-header-marks-face ((,class (:foreground ,nord09))))
   `(mu4e-highlight-face ((,class (:highlight))))
   `(mu4e-link-face ((,class (:underline t))))
   `(mu4e-title-face ((,class (:foreground ,nord08))))
   `(mu4e-unread-face ((,class (:foreground ,nord13 :weight normal))))
   `(neo-banner-face ((,class (:foreground ,nord10))))
   `(neo-dir-link-face ((,class (:foreground ,nord09))))
   `(neo-expand-btn-face ((,class (:foreground ,nord06 :normal t))))
   `(neo-file-link-face ((,class (:foreground ,nord04))))
   `(neo-root-dir-face ((,class (:foreground ,nord07 :weight normal))))
   `(neo-vc-added-face ((,class (:foreground ,nord14))))
   `(neo-vc-conflict-face ((,class (:foreground ,nord11))))
   `(neo-vc-default-face ((,class (:foreground ,nord04))))
   `(neo-vc-edited-face ((,class (:foreground ,nord13))))
   `(neo-vc-ignored-face ((,class (:foreground ,nord03))))
   `(neo-vc-missing-face ((,class (:foreground ,nord12))))
   `(neo-vc-needs-merge-face ((,class (:background ,nord12 :foreground ,nord04))))
   `(neo-vc-needs-update-face ((,class (:background ,nord10 :foreground ,nord04))))
   `(neo-vc-removed-face ((,class (:foreground ,nord11 :strike-through nil))))
   `(neo-vc-up-to-date-face ((,class (:foreground ,nord04))))
   `(neo-vc-user-face ((,class (:foreground ,nord04))))
   `(next-error ((,class (:inherit error))))
   `(nobreak-space ((,class (:foreground ,nord03))))
   `(orderless-match-face-0 ((,class (:foreground ,nord11))))
   `(orderless-match-face-1 ((,class (:foreground ,nord12))))
   `(orderless-match-face-2 ((,class (:foreground ,nord13))))
   `(orderless-match-face-3 ((,class (:foreground ,nord14))))
   `(org-agenda-date ((,class (:foreground ,nord08 :underline nil))))
   `(org-agenda-date-today ((,class (:foreground ,nord08 :weight normal))))
   `(org-agenda-date-weekend ((,class (:foreground ,nord09))))
   `(org-agenda-dimmed-todo-face ((,class (:background ,nord13))))
   `(org-agenda-done ((,class (:foreground ,nord14))))
   `(org-agenda-done ((,class (:foreground ,nord14))))
   `(org-agenda-structure ((,class (:foreground ,nord09))))
   `(org-block ((,class (:foreground ,nord04))))
   `(org-block-background ((,class (:background ,nord00))))
   `(org-block-begin-line ((,class (:foreground ,nord07))))
   `(org-block-end-line ((,class (:foreground ,nord07))))
   `(org-checkbox ((,class (:foreground ,nord09))))
   `(org-checkbox-statistics-done ((,class (:foreground ,nord14))))
   `(org-checkbox-statistics-todo ((,class (:foreground ,nord13))))
   `(org-code ((,class (:foreground ,nord07))))
   `(org-column ((,class (:background ,nord02))))
   `(org-column-title ((,class (:inherit org-column :weight normal :underline t))))
   `(org-date ((,class (:foreground ,nord08))))
   `(org-document-info ((,class (:foreground ,nord04))))
   `(org-document-info-keyword ((,class (:foreground ,nord03 :weight normal))))
   `(org-document-title ((,class (:foreground ,nord08 :weight normal))))
   `(org-done ((,class (:foreground ,nord14 :weight normal))))
   `(org-ellipsis ((,class (:foreground ,nord03))))
   `(org-footnote ((,class (:foreground ,nord08))))
   `(org-formula ((,class (:foreground ,nord09))))
   `(org-hide ((,class (:foreground ,nord00 :background ,nord00))))
   `(org-level-1 ((,class (:foreground ,nord08 :weight normal))))
   `(org-level-2 ((,class (:inherit org-level-1))))
   `(org-level-3 ((,class (:inherit org-level-1))))
   `(org-level-4 ((,class (:inherit org-level-1))))
   `(org-level-5 ((,class (:inherit org-level-1))))
   `(org-level-6 ((,class (:inherit org-level-1))))
   `(org-level-7 ((,class (:inherit org-level-1))))
   `(org-level-8 ((,class (:inherit org-level-1))))
   `(org-link ((,class (:underline t))))
   `(org-quote ((,class (:inherit org-block :slant italic))))
   `(org-scheduled ((,class (:foreground ,nord14))))
   `(org-scheduled-previously ((,class (:foreground ,nord13))))
   `(org-scheduled-today ((,class (:foreground ,nord08))))
   `(org-sexp-date ((,class (:foreground ,nord07))))
   `(org-special-keyword ((,class (:foreground ,nord09))))
   `(org-table ((,class (:foreground ,nord09))))
   `(org-todo ((,class (:foreground ,nord13 :weight normal))))
   `(org-upcoming-deadline ((,class (:foreground ,nord12))))
   `(org-verbatim ((,class (:foreground ,nord07))))
   `(org-verse ((,class (:inherit org-block :slant italic))))
   `(org-warning ((,class (:foreground ,nord13 :weight normal))))
   `(outline-1 ((,class (:foreground ,nord08 :weight normal))))
   `(outline-2 ((,class (:inherit outline-1))))
   `(outline-3 ((,class (:inherit outline-1))))
   `(outline-4 ((,class (:inherit outline-1))))
   `(outline-5 ((,class (:inherit outline-1))))
   `(outline-6 ((,class (:inherit outline-1))))
   `(outline-7 ((,class (:inherit outline-1))))
   `(outline-8 ((,class (:inherit outline-1))))
   `(package-description ((,class (:foreground ,nord04))))
   `(package-help-section-name ((,class (:foreground ,nord08 :weight normal))))
   `(package-name ((,class (:foreground ,nord08))))
   `(package-status-avail-obso ((,class (:foreground ,nord07 :slant italic))))
   `(package-status-available ((,class (:foreground ,nord07))))
   `(package-status-built-in ((,class (:foreground ,nord09))))
   `(package-status-dependency ((,class (:foreground ,nord08 :slant italic))))
   `(package-status-disabled ((,class (:foreground ,nord03))))
   `(package-status-external ((,class (:foreground ,nord12 :slant italic))))
   `(package-status-held ((,class (:foreground ,nord04 :weight normal))))
   `(package-status-incompat ((,class (:foreground ,nord11))))
   `(package-status-installed ((,class (:foreground ,nord07 :weight normal))))
   `(package-status-new ((,class (:foreground ,nord14))))
   `(package-status-unsigned ((,class (:underline ,nord13))))
   `(popup-tip-face ((,class (:background ,nord03 :foreground ,nord06))))
   `(powerline-active1 ((,class (:foreground ,nord04 :background ,nord01))))
   `(powerline-active2 ((,class (:foreground ,nord04 :background ,nord03))))
   `(powerline-evil-base-face ((,class (:foreground ,nord04))))
   `(powerline-evil-insert-face ((,class (:foreground ,nord00 :background ,nord04))))
   `(powerline-evil-normal-face ((,class (:background ,nord08))))
   `(powerline-evil-replace-face ((,class (:foreground ,nord00 :background ,nord09))))
   `(powerline-evil-visual-face ((,class (:foreground ,nord00 :background ,nord07))))
   `(powerline-inactive1 ((,class (:background ,nord02))))
   `(powerline-inactive2 ((,class (:background ,nord02))))
   `(query-replace ((,class (:foreground ,nord08 :background ,nord02))))
   `(rainbow-delimiters-depth-1-face ((,class :foreground ,nord07)))
   `(rainbow-delimiters-depth-2-face ((,class :foreground ,nord08)))
   `(rainbow-delimiters-depth-3-face ((,class :foreground ,nord09)))
   `(rainbow-delimiters-depth-4-face ((,class :foreground ,nord10)))
   `(rainbow-delimiters-depth-5-face ((,class :foreground ,nord12)))
   `(rainbow-delimiters-depth-6-face ((,class :foreground ,nord13)))
   `(rainbow-delimiters-depth-7-face ((,class :foreground ,nord14)))
   `(rainbow-delimiters-depth-8-face ((,class :foreground ,nord15)))
   `(rainbow-delimiters-unmatched-face ((,class :foreground ,nord11)))
   `(region ((,class (:foreground ,nord00 :background ,nord08))))
   `(scroll-bar ((,class (:background ,nord03))))
   `(secondary-selection ((,class (:background ,nord02))))
   `(show-paren-match-face ((,class (:foreground ,nord00 :background ,nord08))))
   `(show-paren-mismatch-face ((,class (:background ,nord11))))
   `(success ((,class (:foreground ,nord14))))
   `(term ((,class (:foreground ,nord04 :background ,nord00))))
   `(term-color-black ((,class (:foreground ,nord01 :background ,nord01))))
   `(term-color-blue ((,class (:foreground ,nord08 :background ,nord08))))
   `(term-color-cyan ((,class (:foreground ,nord07 :background ,nord07))))
   `(term-color-green ((,class (:foreground ,nord14 :background ,nord14))))
   `(term-color-magenta ((,class (:foreground ,nord15 :background ,nord15))))
   `(term-color-red ((,class (:foreground ,nord11 :background ,nord11))))
   `(term-color-white ((,class (:foreground ,nord05 :background ,nord05))))
   `(term-color-yellow ((,class (:foreground ,nord13 :background ,nord13))))
   `(tool-bar ((,class (:foreground ,nord04 :background ,nord03))))
   `(tooltip ((,class (:foreground ,nord00 :background ,nord04))))
   `(trailing-whitespace ((,class (:background ,nord11))))
   `(tty-menu-disabled-face ((,class (:foreground ,nord01))))
   `(tty-menu-enabled-face ((,class (:background ,nord02 foreground ,nord04))))
   `(tty-menu-selected-face ((,class (:foreground ,nord08 :underline t))))
   `(undo-tree-visualizer-current-face ((,class (:foreground ,nord08))))
   `(undo-tree-visualizer-default-face ((,class (:foreground ,nord04))))
   `(undo-tree-visualizer-register-face ((,class (:foreground ,nord09))))
   `(undo-tree-visualizer-unmodified-face ((,class (:foreground ,nord04))))
   `(vc-conflict-state ((,class (:foreground ,nord12))))
   `(vc-edited-state ((,class (:foreground ,nord13))))
   `(vc-locally-added-state ((,class (:underline ,nord14))))
   `(vc-locked-state ((,class (:foreground ,nord10))))
   `(vc-missing-state ((,class (:foreground ,nord11))))
   `(vc-needs-update-state ((,class (:foreground ,nord12))))
   `(vc-removed-state ((,class (:foreground ,nord11))))
   `(vc-state-base ((,class (:foreground ,nord04))))
   `(vc-up-to-date-state ((,class (:foreground ,nord08))))
   `(vertical-border ((,class (:foreground ,nord02))))
   `(web-mode-attr-tag-custom-face ((,class (:foreground ,nord07))))
   `(web-mode-builtin-face ((,class (:foreground ,nord09))))
   `(web-mode-comment-face ((,class (:foreground ,nord03))))
   `(web-mode-comment-keyword-face ((,class (:foreground ,nord03))))
   `(web-mode-constant-face ((,class (:foreground ,nord04))))
   `(web-mode-css-at-rule-face ((,class (:foreground ,nord12))))
   `(web-mode-css-function-face ((,class (:foreground ,nord08))))
   `(web-mode-css-property-name-face ((,class (:foreground ,nord09))))
   `(web-mode-css-pseudo-class-face ((,class (:foreground ,nord07))))
   `(web-mode-css-selector-face ((,class (:foreground ,nord09))))
   `(web-mode-css-string-face ((,class (:foreground ,nord14))))
   `(web-mode-doctype-face ((,class (:foreground ,nord10))))
   `(web-mode-function-call-face ((,class (:foreground ,nord08))))
   `(web-mode-function-name-face ((,class (:foreground ,nord08))))
   `(web-mode-html-attr-equal-face ((,class (:foreground ,nord04))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,nord07))))
   `(web-mode-html-attr-value-face ((,class (:foreground ,nord14))))
   `(web-mode-html-entity-face ((,class (:foreground ,nord09))))
   `(web-mode-html-tag-bracket-face ((,class (:foreground ,nord04))))
   `(web-mode-html-tag-custom-face ((,class (:foreground ,nord09))))
   `(web-mode-html-tag-face ((,class (:foreground ,nord09))))
   `(web-mode-html-tag-namespaced-face ((,class (:foreground ,nord09))))
   `(web-mode-json-key-face ((,class (:foreground ,nord07))))
   `(web-mode-json-string-face ((,class (:foreground ,nord14))))
   `(web-mode-keyword-face ((,class (:foreground ,nord09))))
   `(web-mode-preprocessor-face ((,class (:foreground ,nord10))))
   `(web-mode-string-face ((,class (:foreground ,nord14))))
   `(web-mode-symbol-face ((,class (:foreground ,nord04))))
   `(web-mode-type-face ((,class (:foreground ,nord07))))
   `(web-mode-variable-name-face ((,class (:foreground ,nord04))))
   `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
   `(which-func ((,class (:foreground ,nord08))))
   `(whitespace-big-indent ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-empty ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-hspace ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-indentation ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-line ((,class (:background ,nord00))))
   `(whitespace-newline ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-space ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-space-after-tab ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-space-before-tab ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-tab ((,class (:foreground ,nord03 :background ,nord00))))
   `(whitespace-trailing ((,class (:inherit trailing-whitespace))))
   `(widget-button-pressed ((,class (:foreground ,nord09 :background ,nord01))))
   `(widget-documentation ((,class (:foreground ,nord04))))
   `(widget-field ((,class (:background ,nord02 :foreground ,nord04))))
   `(widget-single-line-field ((,class (:background ,nord02 :foreground ,nord04))))
   `(window-divider ((,class (:background ,nord03))))
   `(window-divider-first-pixel ((,class (:background ,nord03))))
   `(window-divider-last-pixel ((,class (:background ,nord03))))
   `(xref-file-header ((,class (:foreground ,nord14))))
   `(xref-line-number ((,class (:foreground ,nord09))))
   `(xref-match ((,class (:foreground ,nord13))))))

(provide-theme 'nord)
;;; nord-theme.el ends here
